#coding=utf-8
from django.conf.urls import patterns, include, url
#from django.contrib.auth import admin,login,logout
from app.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'it_asset.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    #url(r'$', 'it_asset.views.login', name='home'),
    #url(r'/check_login/', 'it_asset.views.check_login'),
    #url(r'^/index/', 'it_asset.views.index'),
    # url(r'^login/$', 'django.contrib.auth.views.login'),
    # url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login/'}),
    # url(r'^password_change/$', 'django.contrib.auth.views.password_change'),
    # url(r'^password_change_done/$', 'django.contrib.auth.views.password_change_done'),
    # url(r'^password_reset/$', 'django.contrib.auth.views.password_reset'),
    # url(r'password_reset_done/$', 'django.contrib.auth.views.password_reset_done'),
    # url(r'login/', 'app.views.login', name='login'),
    (r'^$', login),
    #(r'^admin/', admin),
    (r'^index/', index),
    (r'^login/', login),
    #(r'^login/', 'views.login'),
    #url(r'login/', 'app.views.logout_view', name='login'),
    (r'^check_login', check_login),
    (r'^new_rack', new_rack),
    (r'^rack_jgt', rack_jgt),
    (r'^rack_list', rack_list),
    (r'^ajax_rack_list', ajax_rack_list),
    (r'^rack_config', rack_config),
    (r'^new_rack_config', new_rack_config),
    (r'^network_config', network_config),
    (r'^new_network_config', new_network_config),
    (r'^getNetwork_configById', getNetwork_configById),
    (r'^deleteNetwork_configById', deleteNetwork_configById),
    (r'^ajax_network_config', ajax_network_config),
    #(r'^new_network_config', new_network_config),
    (r'^server', server),
    (r'^new_server', new_server),
    (r'^ajaxserver', ajaxserver),
    (r'^getServerById', getServerById),
    (r'^deleteServerById', deleteServerById),
    (r'^vm', vm),
    (r'^new_vm', new_vm),
    (r'^getVmById', getVmById),
    (r'^deleteVmById', deleteVmById),
    (r'^ajax_vm', ajax_vm),
    (r'^statistics', statistics),
    (r'^users', users),
    (r'^new_users', new_users),
    (r'^ajax_users', ajax_users),
    (r'^getUsersByID', getUsersById),
    (r'^deleteUsersById', deleteUsersById),
    (r'^logout_view', logout_view),
    (r'^room_list', room_list),
    (r'^ajaxroomlist', ajaxroomlist),
    (r'^getRoomById', getRoomById),
    (r'^deleteRoomById', deleteRoomById),
    (r'^new_room', new_room),
    (r'^service_provider', service_provider),
    (r'^new_service_provider', new_service_provider),
    (r'^ajax_service_provider', ajax_service_provider),
    (r'^getService_providerById', getService_providerById),
    (r'^deleteService_providerById', deleteService_providerById),
    (r'^html', html),
    (r'^getRackById', getRackById),
    (r'^deleteRackById', deleteRackById),
    (r'^ajaxserver', ajaxserver),

)
